version: '3.9'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
    ports:
      - 5432:5432
    volumes:
      - ./migrations/0001_creat_table_clientes.sql:/docker-entrypoint-initdb.d/0001_creat_table_clientes.sql

  api:
    restart: always
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db

# sudo docker exec -it dart_docker_postgres_back_end_db_1 bash
# psql -U postgres
# SELECT * FROM clientes
